sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

language: scala

scala:
  - 2.13.1
  - 2.12.10
  - 2.11.12
jdk:
  - openjdk8
  - openjdk11

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport coveralls
