sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

language: scala

scala:
  - 2.13.1
  - 2.12.10
jdk:
  - openjdk8
  - openjdk11


script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - sbt coverageReport coveralls
